# Warning: do not use tabs, only spaces!
---
excludes:
    [
    data.DURATION,
    data.DURATION.cmn,
    data.DURATION.mensural,
    data.KEYSIGNATURE,
    data.MODUSMAIOR,
    data.MODUSMINOR,
    data.OCTAVE.DIS,
    data.PROLATIO,
    data.STEMDIRECTION.basic,
    data.STEMDIRECTION.extended,
    data.TEMPUS,
    # string
    data.URI
    
    ]
    
mapped:
    data.AUGMENTDOT:
        int
    data.BEAM:
        std::string    
    data.BEAT:
        double
    data.BEND.AMOUNT:
        std::string
    data.COLOR:
        std::string
    data.CLEFLINE:
        char
    data.DURATION.additive:
        data_DURATION
    data.DURATION.cmn: 
        data_DURATION
    data.DURATION.gestural:
        data_DURATION
    data.DURATION.gestural.prop:
        data_DURATION
    data.FILL:
        std::string
    data.FONTFAMILY:
        std::string
    data.FONTNAME:
        std::string
    data.FONTSIZE:
        std::string
    data.HEADSHAPE:
        std::string
    data.ISODATE:
        std::string
    data.ISOTIME:
        std::string
    data.KEYSIGTOKEN:
        std::string
    data.LINESTARTENDSYMBOLSIZE:
        std::string
    data.LINEWIDTH:
        std::string
    data.MEASUREMENT:
        std::string
    data.MUSICFONT:
        std::string
    data.NOTEHEADMODIFIER:
        std::string
    data.OCTAVE:
        char
    data.PAGE.PANELS:
        std::string
    data.PGSCALE:
        std::string
    data.PERCENT:
        int
    data.PITCHNAME.GES:
        data_PITCHNAME
    data.PITCHNUMBER:
        int
    data.ROTATION:
        std::string
    data.SLASH:
        char
    data.SLUR:
        std::string
    data.STAFFLOC:
        int
    data.TEMPOVALUE:
        std::string
    data.TSTAMPOFFSET:
        double
    data.TUPLET:
        std::string
    data.URI:
        std::string

defaults:
    data_MEASUREBEAT:
        std::make_pair(-1,-1.0)
    xsd_posIntList:
        std::vector<int>()

modules:
    shared:    
        att.barLine.log:
            form: 
                default: BARRENDITION_single
        att.common:
            n: 
                type: int
        att.curvature:
            bulge:
                type: double
        att.duration.ratio:
            num: 
                default: -1
            numbase: 
                default: -1
        att.measure.log:
            right: 
                default: BARRENDITION_single
        att.meterSig.log:
            count: 
                type: int
            unit: 
                type: int
        att.meterSigDefault.log:
            meter.count: 
                type: int
            meter.unit: 
                type: int
        att.staffident:
            staff: 
                type: xsd_posIntList
        att.timestamp.musical:
            tstamp:
                default: -1.0

    mensural:
        att.mensural.log:
            proport.num:
                default: -1
            proport.numbase:
                default: -1  

att-classes:
  - id: "accidental"
    attributes:
    - ["accid", "Supported values are 's', 'f', 'n', 'x', 'ff', 'ns' and 'nf'.", ""]
  - id: "barLine.log"
    attributes:
    - ["rend", "Supported values are: 'single', 'rptboth', 'rptstart', 'rptend', 'dbl', and 'end'.", ""]
  - id: "cleffing.log"
    attributes:
    - ["clef.shape", "Supported values are 'C', 'F' and 'G'.", ""]
    - ["clef.line", "Supported values are 1-5 for shape 'C', 1-2 for 'G' and 3-5 for 'F'.", ""]
    - ["clef.dis", "Only value '8' is supported and it assumes shape 'G' and line 2.", ""]
    - ["clef.place", "Supported values: 'below'", ""]
  
interfaces:
  - id: "pitchInterface"
    att-classes:
      - accidental
      - octave
      - pitch
classes:
  - id: "note"
    interfaces:
      - pitchInterface
    att-classes:
      - coloration
      - grace
      - stemmed
      - note.log.mensural
    attributes: []
  - id: "app"
    att-classes:
      - common
    attributes: []
  - id: "beam"
  - id: "barLine"
    att-classes:
      - barLine.log

