# Warning: do not use tabs, only spaces!
---
excludes:
    data.DURATION:
        type: data_DURATION
        default: DURATION_NONE
    data.DURATION.cmn:
        type: data_DURATION
        default: DURATION_NONE
    data.DURATION.mensural:
        type: data_DURATION
        default: DURATION_NONE
    data.KEYSIGNATURE:
        type: data_KEYSIGNATURE
        default: KEYSIGNATURE_NONE
    data.MODUSMAIOR:
        type: data_MODUSMAIOR
        default: MODUSMAIOR_NONE
    data.MODUSMINOR:
        type: data_MODUSMINOR
        default: MODUSMINOR_NONE
    data.OCTAVE.DIS:
        type: data_OCTAVE_DIS
        default: OCTAVE_DIS_NONE
    data.PROLATIO:
        type: data_PROLATIO
        default: PROLATIO_NONE
    data.TEMPUS:
        type: data_TEMPUS
        default: TEMPUS_NONE

defaults:
    int:
        default: 0
        converters: [StrToInt, IntToStr]
    char: 
        default: 0
        converters: [StrToInt, IntToStr]
    double: 
        default: 0.0
        converters: [StrToDbl, DblToStr]
    data_PERCENT:
        default: 0
        #converters: [StrToPercent, PercentToStr]
    typedef_TSTAMP2:
        default: std::make_pair(-1,-1.0)
        #converters: [StrToTstamp2, Tstamp2ToStr]
modules:
    shared:
        attributes:
            # att.augmentdots
            dots:
                type: char            
            # att.barLine.log
            rend: 
                type: data_BARRENDITION
                default: BARRENDITION_single
            # att.common
            n: 
                type: int
            # att.cleffing.log
            clef.line: 
                type: char
            clef.dis: 
                type: data_OCTAVE_DIS
            # att.curvature
            bulge:
                type: double
            # att.duration.musical
            dur: 
                type: data_DURATION
            # att.duration.performed
            dur.ges: 
                type: data_DURATION
            # att.duration.ratio
            num: 
                type: int
                default: -1
            numbase: 
                type: int
                default: -1
            # att.keySigDefault.log
            key.sig: 
                type: data_KEYSIGNATURE
            # att.lineloc
            line: 
                type: char
            # att.measure.log
            right: 
                type: data_BARRENDITION
                default: BARRENDITION_single
            # att.meterSig.log
            count: 
                type: int
            unit: 
                type: int
            # att.meterSigDefault.log
            meter.count: 
                type: int
            meter.unit: 
                type: int
            # att.octave
            oct: 
                type: char
            # att.octavedisplacement
            dis: 
                type: data_OCTAVE_DIS
            # att.scalable
            scale:
                type: data_PERCENT
            # att.slashcount
            slash: 
                type: char
            # att.staffident
            staff: 
                type: int
            # att.staffloc.pitched
            oloc: 
                type: char
            stem.len: 
                type: int
            stem.x: 
                type: int
            stem.y: 
                type: int
            # att.timestamp.musical
            tstamp:
                type: double
                default: -1.0
            # att.timestamp2.musical
            tstamp2:
                type: typedef_TSTAMP2

    cmn:
        attributes:
            # att.beatRpt.vis
            rend:
                type: data_BEATRPT_REND
                default: BEATRPT_REND_NONE

    mensural:
        attributes:
            # att.mensural.log
            mensur.slash: 
                type: char
            proport.num: 
                type: int
                default: -1
            proport.numbase:
                type: int
                default: -1  
            # att.mensural.shared
            modusmaior:
                type: data_MODUSMAIOR
            modusminor:
                type: data_MODUSMINOR
            prolatio:
                type: data_PROLATIO
            tempus:
                type: data_TEMPUS

                
att-classes:
  - id: "accidental"
    attributes:
    - ["accid", "Supported values are 's', 'f', 'n', 'x', 'ff', 'ns' and 'nf'.", ""]
  - id: "barLine.log"
    attributes:
    - ["rend", "Supported values are: 'single', 'rptboth', 'rptstart', 'rptend', 'dbl', and 'end'.", ""]
  - id: "cleffing.log"
    attributes:
    - ["clef.shape", "Supported values are 'C', 'F' and 'G'.", ""]
    - ["clef.line", "Supported values are 1-5 for shape 'C', 1-2 for 'G' and 3-5 for 'F'.", ""]
    - ["clef.dis", "Only value '8' is supported and it assumes shape 'G' and line 2.", ""]
    - ["clef.place", "Supported values: 'below'", ""]
  
interfaces:
  - id: "pitchInterface"
    att-classes:
      - accidental
      - octave
      - pitch
classes:
  - id: "note"
    interfaces:
      - pitchInterface
    att-classes:
      - coloration
      - grace
      - stemmed
      - note.log.mensural
    attributes: []
  - id: "app"
    att-classes:
      - common
    attributes: []
  - id: "beam"
  - id: "barLine"
    att-classes:
      - barLine.log

